- name: Restore token.json
  run: |
    TOKEN=""
    i=0
    while true; do
      PART=$(printenv YT_TOKEN_$i)
      if [ -z "$PART" ]; then
        break
      fi
      TOKEN="$TOKEN$PART"
      i=$((i+1))
    done
    echo $TOKEN | base64 --decode > token.json
